DATA:
    fn: 'timing.csv' # timing.csv or power.csv
HYPERPARAMETER:
    LGBM:
        boosting_type: 'gbdt' # 'gbdt', 'rf', 'dart', 'goss'
        objective: 'regression'
        metric: 'l1'
        num_leaves: 31
        learning_rate: 0.05
        feature_fraction: 0.9
        bagging_fraction: 0.8
        bagging_freq: 5
        verbose: 0
        epoch: 200
SAVED:
    model_fn: 'saved/model.txt'